package com.example.dist_app.products.model;

import jakarta.persistence.*;

/**
 * JPA entity representing a product in the catalog.
 * This class models the core product information stored in the database,
 * including identifying information, pricing, and physical attributes.
*
 * <p>Products can be queried by color using the predefined named queries:</p>
 * <ul>
 *   <li>{@code Product.findBlackProducts} - Retrieves all black-colored products</li>
 *   <li>{@code Product.findRedProducts} - Retrieves all red-colored products</li>
 *   <li>{@code Product.findBlueProducts} - Retrieves all blue-colored products</li>
 * </ul>
 */
@Entity
@NamedQueries({
    @NamedQuery(name="Product.findBlackProducts", query="SELECT p FROM Product p WHERE p.color = 'black'"),
    @NamedQuery(name="Product.findRedProducts", query="SELECT p FROM Product p WHERE p.color = 'red'"),
    @NamedQuery(name="Product.findBlueProducts", query="SELECT p FROM Product p WHERE p.color = 'blue'")
})
public class Product {

    /**
     * Unique identifier for the product, auto-generated by the database.
     * Used as the primary key for product lookups and references.
     */
    @Id @GeneratedValue
    private Long id;

    /**
     * The display name of the product shown to customers.
     * Should be descriptive and unique within the catalog.
     */
    private String name;

    /**
     * The price of the product in Euros.
     * Represented as a Double for decimal precision in currency calculations.
     */
    private Double price;

    /**
     * The size of the product as a numeric value.
     * The unit of measurement depends on the product category (e.g., clothing size, dimensions).
     */
    private Long size;

    /**
     * The color of the product as a string value.
     * Common values include "black", "red", "blue" which can be used with named queries.
     */
    private String color;

    /**
     * Constructs a new Product with the specified attributes.
     *
     * @param name the display name of the product
     * @param price the price in Euros
     * @param size the size value of the product
     * @param color the color of the product
     */
    public Product(String name, Double price,  Long size, String color) {
        this.name = name;
        this.price = price;
        this.size = size;
        this.color = color;
    }

    /**
     * Default no-argument constructor required by JPA.
     */
    public Product() {

    }

    /**
     * Returns the unique identifier of this product.
     *
     * @return the product ID as a Long value
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the unique identifier for this product.
     *
     * @param id the product ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the display name of this product.
     *
     * @return the product name as a String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the display name for this product.
     *
     * @param name the product name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the price of this product in Euros.
     *
     * @return the product price as a Double value
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Sets the price for this product.
     *
     * @param price the price in Euros to set
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * Returns the size of this product.
     *
     * @return the product size as a Long value
     */
    public Long getSize() {
        return this.size;
    }

    /**
     * Sets the size for this product.
     *
     * @param size the size value to set
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * Returns the color of this product.
     *
     * @return the product color as a String
     */
    public String getColor() {
        return this.color;
    }

    /**
     * Sets the color for this product.
     *
     * @param color the color to set (e.g., "black", "red", "blue")
     */
    public void setColor(String color) {
        this.color = color;
    }
}
